services:

  postgres:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=example"

  elastic-search:
    image: "elasticsearch:8.14.1"
    ports:
      - "9300:9300"
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
